config/routes.rb
Rails.application.routes.draw do
  resources :myfiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/myfile.rb
class Myfile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/myfiles_controller.rb
class MyfilesController < ApplicationController
  before_action :set_myfile, only: %i[ show edit update destroy ]

  # GET /myfiles or /myfiles.json
  def index
    @myfiles = Myfile.all
  end

  # GET /myfiles/1 or /myfiles/1.json
  def show
  end

  # GET /myfiles/new
  def new
    @myfile = Myfile.new
  end

  # GET /myfiles/1/edit
  def edit
  end

  # POST /myfiles or /myfiles.json
  def create
    @myfile = Myfile.new(myfile_params)

    respond_to do |format|
      if @myfile.save
        format.html { redirect_to myfile_url(@myfile), notice: "Myfile was successfully created." }
        format.json { render :show, status: :created, location: @myfile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @myfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myfiles/1 or /myfiles/1.json
  def update
    respond_to do |format|
      if @myfile.update(myfile_params)
        format.html { redirect_to myfile_url(@myfile), notice: "Myfile was successfully updated." }
        format.json { render :show, status: :ok, location: @myfile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @myfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myfiles/1 or /myfiles/1.json
  def destroy
    @myfile.destroy

    respond_to do |format|
      format.html { redirect_to myfiles_url, notice: "Myfile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myfile
      @myfile = Myfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def myfile_params
      params.require(:myfile).permit(:name, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myfiles_helper.rb
module MyfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DelayedJob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/myfiles/_form.html.erb
<%= form_with(model: myfile) do |form| %>
  <% if myfile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(myfile.errors.count, "error") %> prohibited this myfile from being saved:</h2>

      <ul>
        <% myfile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/myfiles/_myfile.html.erb
<div id="<%= dom_id myfile %>">
  <p>
    <strong>Name:</strong>
    <%= myfile.name %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= myfile.text %>
  </p>

</div>

app/views/myfiles/edit.html.erb
<h1>Editing myfile</h1>

<%= render "form", myfile: @myfile %>

<br>

<div>
  <%= link_to "Show this myfile", @myfile %> |
  <%= link_to "Back to myfiles", myfiles_path %>
</div>

app/views/myfiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Myfiles</h1>

<div id="myfiles">
  <% @myfiles.each do |myfile| %>
    <%= render myfile %>
    <p>
      <%= link_to "Show this myfile", myfile %>
    </p>
  <% end %>
</div>

<%= link_to "New myfile", new_myfile_path %>

app/views/myfiles/new.html.erb
<h1>New myfile</h1>

<%= render "form", myfile: @myfile %>

<br>

<div>
  <%= link_to "Back to myfiles", myfiles_path %>
</div>

app/views/myfiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @myfile %>

<div>
  <%= link_to "Edit this myfile", edit_myfile_path(@myfile) %> |
  <%= link_to "Back to myfiles", myfiles_path %>

  <%= button_to "Destroy this myfile", @myfile, method: :delete %>
</div>